export const DASHBOARD_INIT="DASHBOARD_INIT";
export const FETCH_DASHBOARD_SUCCESS="FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAIL="FETCH_DASHBOARD_FAIL";

export const STATS_INIT="STATS_INIT";
export const FETCH_STATS_SUCCESS="FETCH_STATS_SUCCESS";
export const FETCH_STATS_FAIL="FETCH_STATS_FAIL";